name: BuildAndDeploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    environment: SLS
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2.2.2
      with:
          version: 6.0.2
            
    - name: Install dependencies
      run: pnpm i || pnpm i || pnpm i

    
    
    - name: SetupSSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: RunDeployScript
      run: sh deploy.sh ${{ secrets.SSH_HOST }}
